---
image: robertdebock/github-action-molecule:3.0.6

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "debian"
        tag: "latest"
      - image: "rockylinux"
        tag: "latest"
      - image: "fedora"
        tag: "33"
      - image: "opensuse"
        tag: "latest"
      - image: "ubuntu"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
