---
# tasks file for nextcloud

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  ansible.builtin.package:
    name: "{{ nextcloud_requirements }}"
    state: present

- name: place apache configuration
  ansible.builtin.template:
    src: nextcloud.conf.j2
    dest: "{{ nextcloud_config_directory }}/nextcloud.conf"
    mode: "0644"

- name: modify selinux settings
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  loop: "{{ nextcloud_sebooleans }}"

- name: install nextcloud
  ansible.builtin.unarchive:
    src: "{{ nextcloud_archive }}"
    dest: "{{ nextcloud_destination }}"
    remote_src: yes
    owner: "{{ nextcloud_httpd_owner }}"
    group: "{{ nextcloud_httpd_group }}"
    creates: "{{ nextcloud_destination }}/nextcloud/occ"
    mode: "0775"

- name: configure nextcloud
  ansible.builtin.command:
    cmd: "{{ nextcloud_command }}"
    creates: "{{ nextcloud_destination }}/nextcloud/data/index.html"
    chdir: "{{ nextcloud_destination }}/nextcloud"
  no_log: yes
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"
  notify:
    - set memcache.distributed
    - set redis host
    - set redis port
    - set trusted domains
    - set permissions
    - add missing indices

- name: install nextcloud app
  ansible.builtin.command:
    cmd: php occ app:install {{ item.name }}
    chdir: "{{ nextcloud_destination }}/nextcloud"
    creates: "{{ nextcloud_destination }}/nextcloud/apps/{{ item.name }}"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"
  loop: "{{ nextcloud_apps }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nextcloud_apps is defined
  notify:
    - set permissions

- name: include parameters
  ansible.builtin.include_tasks:
    file: parameters.yml
  loop: "{{ nextcloud_settings }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nextcloud_settings is defined

- name: setup crontab
  ansible.builtin.cron:
    name: nextcloud
    minute: "*/5"
    hour: "*"
    job: "php {{ nextcloud_destination }}/nextcloud/occ system:cron"
    user: "{{ nextcloud_httpd_owner }}"
