---
# handlers file for nextcloud

- name: set memcache.distributed
  ansible.builtin.command:
    cmd: php occ config:system:set memcache.distributed --value="\OC\Memcache\Redis"
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"

- name: set redis host
  ansible.builtin.command:
    cmd: php occ config:system:set redis host --value="localhost"
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"

- name: set redis port
  ansible.builtin.command:
    cmd: php occ config:system:set redis port --value="6379"
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"

- name: set trusted domains
  ansible.builtin.command:
    cmd: php occ config:system:set trusted_domains 1 --value={{ nextcloud_domain_url }}
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"

- name: set permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ nextcloud_permissions }}"
  loop_control:
    label: "{{ item.path }}"

- name: add missing indices
  ansible.builtin.command:
    cmd: php occ db:add-missing-indices
  args:
    chdir: "{{ nextcloud_destination }}/nextcloud"
  become: yes
  become_user: "{{ nextcloud_httpd_owner }}"
